### PR TITLE
Upgrade mozdownload and mozinstall to latest version (#204)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #204 for the master branch. @andreeamatei could you have a look at it please? Thanks.

### CODE REVIEW

**Comment by whimboo** [comment]
No-one actually told me that we still suffer from bug 969334 with mozinstall. OS X 10.6-1 had this problem showing again. So we may need another bump later for mozinstall. :(

**Comment by andreeamatei** [comment]
lgtm

**Comment by whimboo** [comment]
Thanks Andreea. I have to wait the next 30min before I can push this. It's the time when mozilla-inbound gets merged to mozilla-central and I can release mozinstall.

**Comment by whimboo** [comment]
This has been merged as https://github.com/mozilla/mozmill-automation/commit/e4c302bbe61dd3355c9a2f98490828f02bc8e69b

**Pull request closed without merging**
